### ISSUE TITLE
Account Confirmation Link triggers redirect loop

### ISSUE THREAD

**Issue by benjaminwolkchen** [Dashibase/dashibase#17]
**Describe the bug**
Account Confirmation Link triggers redirect loop.

**To Reproduce**
1. Go to a Dashibase Dashboard Signup Page
2. Enter Account Details
3. Open the Confirmation Link you received

**Expected behavior**
After you click on the Confirmation Link, your account should be activated, and you should be greeted with a message that tells you that.

**Screenshots**

https://user-images.githubusercontent.com/42138517/167114330-c6f85d9f-a0f3-411b-ad44-890f0d8096d6.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox (Librewolf)
 - Version 99.0.1-4

But I've also tested it on Microsoft Edge (Chromium) Version 101.0.1210.32 - same behavior.

**Comment by greentfrapp** [comment]
Thanks @benjaminwolkchen for raising this! And sorry for the delay, was out for dinner.

This was an interesting one - the cause is that the Table ID and the Page Name wasn't specified for your particular page in the dashboard (see below). 

![Screenshot 2022-05-07 at 01-16-00 Dashibase](https://user-images.githubusercontent.com/13292973/167180981-4ec79aa2-b0ab-47a8-9330-4a1258d515ad.png)

Because we reference the page by the page name (e.g. in your case https://awesomebible.app.dashibase.com/PAGE_NAME) a blank page name would result in collision with the root URL.

Looking deeper, the root cause is that even though the Table ID and Page Name were specified as required inputs, we didn't enforce the requirement and allowed for creation of pages without these being specified. This has been remedied and we now raise an error message when a page is created or modified to an empty Table ID or Page Name.

**Suggested steps to fix this:**
1. Use our dashboard at https://app.dashibase.com to add a Table ID and Page Name to your page
2. Log in again to your dashboard (you may have to clear your cache / localstorage)

Let me know if this helps?

**Comment by benjaminwolkchen** [comment]
Thank you. Now it works perfectly! 👍
