### ISSUE TITLE
Popup is off the screen

### ISSUE THREAD

**Issue by zernonia** [Dashibase/dashibase#50]
**Describe the bug**
Popup is off the screen

**To Reproduce**
 Click the "dot handle"

**Expected behavior**
Popup show position inside the viewport

**Screenshots**
![image](https://user-images.githubusercontent.com/59365435/175958537-27302fca-fd58-4a33-9fdf-eb9a8205708c.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome 

 
**Additional context**
Screen width: 1004px

**Comment by greentfrapp** [comment]
I thought you had a 34" screen! Haha but thanks for reporting this! For now I've pushed a quick patch to adjust the menu width depending on the viewport width but we'll try to think of a better solution to this.

**Comment by zernonia** [comment]
Hahahah yeah but I often split my screen to left/right, thus rendering about 1000px+ width only 😂

**Comment by greentfrapp** [comment]
Pushed another patch to translate menu so that it aligns with left-hand side of the screen if necessary, in addition to reducing menu width, adopting Notion's solution in similar circumstances.

![Screenshot 2022-06-29 at 00-52-46 Dashibase Insert](https://user-images.githubusercontent.com/13292973/176236897-dc49b1d0-df5a-4792-b556-4e466d7dc74a.png)

Thanks again for reporting this @zernonia! Closing for now
